C ---------------------------------------------------------------------------
C
C ---------------------------------------------------------------------------
      INTEGER(KIND=IK)  GET_NGP, GET_BCT, GET_PLT, GET_GRT, GET_GMT,
     &                  GET_GAT, GET_SPT, GET_ITF, GET_AED, GET_ANW,
     &                  GET_AGP
      EXTERNAL          GET_NGP, GET_BCT, GET_PLT, GET_GRT, GET_GMT,
     &                  GET_GAT, GET_SPT, GET_ITF, GET_AED, GET_ANW,
     &                  GET_AGP
C ---------------------------------------------------------------------------
C
C ---------------------------------------------------------------------------