CSCALE1
      SUBROUTINE SCALE1(N,A,AMAT)
      DOUBLE PRECISION A,AMAT
      DIMENSION A(*),AMAT(N,*)
C
C ... THE SUBROUTINE SCALE1 SCALES THE COLUMNS OF THE MATRIX A
C
      DO 300 I=1,N
         DO 200 J=1,N
            AMAT(J,I)=AMAT(J,I)*A(I)
  200    CONTINUE
  300 CONTINUE
C
C     END OF SCALE1
      RETURN
      END
CSCALE2
      SUBROUTINE SCALE2(N,A,X)
      DOUBLE PRECISION A,X
      DIMENSION A(*),X(*)
C
C ... THE SUBROUTINE SCALE2 COMPUTES THE APPROXIMATION X FROM ITS SCALED
C     VALUES
C
      DO 100 I=1,N
         X(I)=X(I)*A(I)
  100 CONTINUE
C
C     END OF SCALE2
      RETURN
      END