C ---------------------------------------------------------------------------
C
C ---------------------------------------------------------------------------
      INTEGER(KIND=IK) GET_ITR_MAXIT, GET_DOD_MAXIT
      EXTERNAL         GET_ITR_MAXIT, GET_DOD_MAXIT
      REAL   (KIND=RK) GET_INT_ABS, GET_INT_REL,
     &                 GET_ITR_TOL, GET_ITR_OMG,
     &                 GET_DOD_TOL, GET_DOD_OMG
      EXTERNAL         GET_INT_ABS, GET_INT_REL,
     &                 GET_ITR_TOL, GET_ITR_OMG,
     &                 GET_DOD_TOL, GET_DOD_OMG
C ---------------------------------------------------------------------------
C
C ---------------------------------------------------------------------------