C ---------------------------------------------------------------------------
C
C ---------------------------------------------------------------------------
      REAL   (KIND=RK) GET_TIME, GET_TBEG, GET_TEND,
     &                 GET_DELTA_T, GET_PERIOD,
     &                 GET_DELTA_T_MIN,
     &                 GET_DELTA_T_MAX
      INTEGER(KIND=IK) GET_DT_PLT, GET_SUBD_MAX
      EXTERNAL         GET_TIME, GET_TBEG, GET_TEND,
     &                 GET_DELTA_T, GET_DT_PLT, GET_SUBD_MAX, GET_PERIOD
     &                 GET_DELTA_T_MIN,
     &                 GET_DELTA_T_MAX
C ---------------------------------------------------------------------------
C
C ---------------------------------------------------------------------------
